version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 091846656105.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t filebrowser .

  post_build:
    commands:
      - echo Tagging and pushing image to ECR...
      - docker tag filebrowser:latest 091846656105.dkr.ecr.ap-south-1.amazonaws.com/filebrowser:latest
      - docker push 091846656105.dkr.ecr.ap-south-1.amazonaws.com/filebrowser:latest
      - echo Creating imagedefinitions.json...
      - echo '[{"name":"filebrowser","imageUri":"091846656105.dkr.ecr.ap-south-1.amazonaws.com/filebrowser:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
